server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:boeken;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: user
      password: password

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
